# Generated by Django 3.0.8 on 2020-08-18 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='collegeList',
            fields=[
                ('college_id', models.AutoField(db_column='College Id', primary_key=True, serialize=False)),
                ('college_name', models.CharField(db_column='College Name', max_length=100)),
                ('college_city', models.CharField(db_column='College City', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='skillsList',
            fields=[
                ('skill_id', models.AutoField(db_column='Skill Id', primary_key=True, serialize=False)),
                ('skill_name', models.CharField(db_column='Skill Name', max_length=30)),
            ],
        ),
    ]
