# Generated by Django 3.0.8 on 2020-08-18 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userInfo',
            fields=[
                ('username', models.CharField(db_column='Username', max_length=150, primary_key=True, serialize=False)),
                ('contact_no', models.CharField(db_column='Contact No.', max_length=10)),
                ('gender', models.CharField(db_column='Gender', max_length=10)),
                ('college_id', models.IntegerField(db_column='College Id', default=None)),
                ('city', models.CharField(db_column='City', default=None, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='userSkills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_column='Username', max_length=150)),
                ('skill', models.IntegerField(db_column='Skill Name')),
            ],
        ),
    ]
