# Generated by Django 3.0.8 on 2020-08-26 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200826_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='city',
            field=models.CharField(db_column='City', max_length=50),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='college_id',
            field=models.IntegerField(db_column='College Id'),
        ),
    ]
