# Generated by Django 3.0.8 on 2020-08-02 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('contact_no', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('age', models.CharField(max_length=2)),
            ],
        ),
    ]
