# Generated by Django 3.0.8 on 2020-08-26 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200826_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='college_id',
        ),
    ]
