# Generated by Django 3.0.8 on 2020-08-29 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0007_auto_20200827_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userskills',
            name='username',
            field=models.OneToOneField(db_column='Username', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
