# Generated by Django 3.0.8 on 2020-08-29 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
        ('user', '0008_auto_20200829_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userskills',
            name='skill',
            field=models.OneToOneField(db_column='Skill Name', on_delete=django.db.models.deletion.CASCADE, to='adminpanel.skillsList'),
        ),
    ]
