# Generated by Django 3.0.8 on 2020-08-18 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='projectInfo',
            fields=[
                ('project_id', models.AutoField(db_column='Project Id', primary_key=True, serialize=False)),
                ('project_title', models.CharField(db_column='Project Title', max_length=100)),
                ('project_description', models.CharField(db_column='Project Description', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='Creation DateTime')),
            ],
        ),
        migrations.CreateModel(
            name='projectSkills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField(db_column='Project Id')),
                ('skill_id', models.IntegerField(db_column='Skill Id')),
            ],
        ),
        migrations.CreateModel(
            name='userProjectInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_column='User Id', max_length=50)),
                ('user_status', models.CharField(choices=[('Applied', 'Applied'), ('In Touch', 'In Touch'), ('Selected', 'Selected'), ('Rejected', 'Rejected')], max_length=20)),
            ],
        ),
    ]
