# Generated by Django 3.0.8 on 2020-08-18 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userproject', '0002_auto_20200829_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectinfo',
            name='project_owner',
            field=models.CharField(db_column='Project Owner', default=1, max_length=150),
            preserve_default=False,
        ),
    ]
