# Generated by Django 3.0.8 on 2020-08-29 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userproject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectinfo',
            name='end_date',
            field=models.DateTimeField(db_column='End Date', default=None),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='required_contributors',
            field=models.IntegerField(db_column='Required Contributors', default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='start_date',
            field=models.DateTimeField(db_column='Start Date', default=None),
        ),
    ]
