# Generated by Django 3.0.8 on 2020-08-26 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userproject', '0002_projectinfo_project_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprojectinfo',
            name='user_status',
            field=models.CharField(choices=[('Applied', 'Applied'), ('In Touch', 'In Touch'), ('Selected', 'Selected'), ('Rejected', 'Rejected')], default='Applied', max_length=20),
        ),
    ]
