# Generated by Django 3.0.8 on 2020-08-29 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userproject', '0004_auto_20200829_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectinfo',
            name='project_owner',
            field=models.ForeignKey(db_column='Project Owner', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
