# Generated by Django 3.0.8 on 2020-08-29 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
        ('userproject', '0006_auto_20200829_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectskills',
            name='skill_id',
            field=models.ForeignKey(db_column='Skill Id', on_delete=django.db.models.deletion.CASCADE, to='adminpanel.skillsList'),
        ),
    ]
