# Generated by Django 3.0.8 on 2020-09-04 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userproject', '0007_auto_20200829_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprojectinfo',
            name='project_id',
            field=models.ForeignKey(db_column='Project Id', on_delete=django.db.models.deletion.CASCADE, to='userproject.projectInfo'),
        ),
        migrations.AlterField(
            model_name='userprojectinfo',
            name='username',
            field=models.ForeignKey(db_column='Username', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
