# Generated by Django 3.0.8 on 2020-09-08 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userproject', '0009_projectskills_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectskills',
            name='status',
            field=models.CharField(db_column='Status', default='1', max_length=2),
        ),
    ]
