# Generated by Django 3.0.8 on 2020-09-08 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userproject', '0010_auto_20200908_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectskills',
            name='status',
            field=models.BooleanField(db_column='Status', default=True),
        ),
    ]
