# Generated by Django 3.0.8 on 2020-09-08 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userproject', '0013_auto_20200908_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectinfo',
            name='required_contributors',
            field=models.IntegerField(db_column='Required Contributors'),
        ),
    ]
