# Generated by Django 3.0.8 on 2020-09-09 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userproject', '0014_auto_20200908_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectinfo',
            name='end_date',
            field=models.CharField(db_column='End Date', max_length=50),
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='start_date',
            field=models.CharField(db_column='Start Date', max_length=50),
        ),
    ]
