# Generated by Django 3.0.8 on 2020-09-09 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userproject', '0016_auto_20200909_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprojectinfo',
            name='project_id',
        ),
        migrations.RemoveField(
            model_name='userprojectinfo',
            name='username',
        ),
        migrations.AddField(
            model_name='userprojectinfo',
            name='project',
            field=models.ForeignKey(db_column='Project', default=None, on_delete=django.db.models.deletion.CASCADE, to='userproject.projectInfo'),
        ),
        migrations.AddField(
            model_name='userprojectinfo',
            name='user',
            field=models.ForeignKey(db_column='User', default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
